/*
 * Co-WIN Public APIs
 *
 * Co-WIN Public APIs to find appointment availabilty and to download vaccination certificates. These APIs are available for use by all third party applications. <i>[Updated on 30 Apr 2021]</i>
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2003 struct {
	Districts []InlineResponse2003Districts `json:"districts,omitempty"`
	// Time in hours to cache the data. Client applications can use this data for this many number of hours before calling this API again.
	Ttl float64 `json:"ttl,omitempty"`
}
