/*
 * Co-WIN Public APIs
 *
 * Co-WIN Public APIs to find appointment availabilty and to download vaccination certificates. These APIs are available for use by all third party applications. <i>[Updated on 30 Apr 2021]</i>
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SessionCalendarEntrySchemaSessions struct {
	SessionId         string  `json:"session_id"`
	Date              string  `json:"date"`
	AvailableCapacity float64 `json:"available_capacity"`
	MinAgeLimit       float64 `json:"min_age_limit"`
	Vaccine           string  `json:"vaccine"`
	// Array of slot names
	Slots []string `json:"slots"`
}
